### ISSUE TITLE
pre-training model

### ISSUE THREAD

**Issue by fengyanWang** [alessandrolamberti/joint-segmentation-depth#1]
Thank you very much for your open source work. Do you have a pre-training model? I want to quickly verify the effect of the model in my use scenario

**Comment by alessandrolamberti** [comment]
Hey @fengyanWang!
The original pre-trained models are opensourced by the author of the paper and can be found at [https://github.com/DrSleep/multi-task-refinenet/tree/master/weights](https://github.com/DrSleep/multi-task-refinenet/tree/master/weights)
